trigger:
-none  # abhi none select ker rakha hai ni to dev rakh lena kyoki hum dev main push ho to trigger ho ye feature chahte hai

variables:
- group: Variable_Group_Rabbit_Mq_Password   # variable group for secrets like rabbitmqPasswordd
- group: service_principle_credentials 
- name: imageName
  value: 'weatherapp'
- name: acrName
  value: 'acrlearn001.azurecr.io'
- name: acrserviceconnection
  value: 'acr_serviceconnection'
- name: sshServiceConnection
  value: 'ssh-service-connection'
- name: vmAppPath
  value: '/home/azureuser/weatherapp'
# ==============================
# BUILD STAGE
# ==============================
stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    pool:
      name: 'SelfHosted-AgentPool'
    steps:
    - checkout: self
    - task: Docker@2
      inputs:
        command: buildAndPush
        containerRegistry: '$(acrserviceconnection)'
        repository: '$(imageName)'
        dockerFile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
# ==============================
# DEPLOY STAGE
# ==============================
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToVM
    pool:
      name: 'SelfHosted-AgentPool'
    steps:
    # Single SSH task: mkdir, copy compose, login, deploy
    - task: SSH@0
      inputs:
        sshEndpoint: $(sshServiceConnection)
        runOptions: commands
        failOnStdErr: false
        commands: |
          # Ensure target folder exists
          mkdir -p $(vmAppPath)
          cd $(vmAppPath)

          # Copy docker-compose.yml from repo to VM directly into target folder
          cp $(System.DefaultWorkingDirectory)/WeatherApps/docker-compose.yml .  # here dot mean current path 

          # Login to ACR using Service Principal
          echo $(acrServicePrincipalSecreteVal) | docker login $(acrName) -u $(acrServicePrincipalClientId) --password-stdin

          # Set image tag and deploy using Docker Compose
          # Write .env file for Docker Compose
          echo "IMAGE_TAG=$(Build.BuildId)" > .env  # Create new file (or overwrite if exists) and write content
         
          docker compose pull
          docker compose down || true
          docker compose up -d --remove-orphans
          
