trigger:
- dev

variables:
- group: Variable_Group_Rabbit_Mq_Password   # variable group for secrets like rabbitmqPassword
- group: service_principle_credentials 
- name: imageName
  value: 'weatherapp'
- name: acrName
  value: 'acrlearn001.azurecr.io'
- name: acrserviceconnection
  value: 'acr_serviceconnection'
- name: sshServiceConnection
  value: 'ssh-service-connection'
- name: vmAppPath
  value: '/home/ubuntu/weatherapp'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    pool:
      name: 'SelfHosted-AgentPool'
    steps:
    - checkout: self
    - task: Docker@2
      inputs:
        command: buildAndPush
        containerRegistry: 'acr_serviceconnection'  #$(acrserviceconnection)
        repository: '$(imageName)'
        dockerFile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToVM
    pool:
      name: 'SelfHosted-AgentPool'
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: $(sshServiceConnection)
        runOptions: commands
        commands: |
          mkdir -p $(vmAppPath)
          cd $(vmAppPath)
          
          # Login to ACR using SP (Service Principal)
          echo $(acrServicePrincipalSecreteVal) | docker login $(acrName) -u $(acrServicePrincipalClientId) --password-stdin
                   
          # Pull the built image
          docker pull $(acrName)/$(imageName):$(Build.BuildId)
          
          # Stop old containers if running
          docker-compose down || true
            # Start new containers
          docker-compose up -d
