services:

  rabbitmq: # ye service ka name hai aur service ka name api se bhi yahi call hoga aur container main jab service run hoti hai to service ka name likha jata hai na ki local host.
    image: rabbitmq:3-management
    container_name: rabbit-mq-container
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  weatherapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weatherApp
    depends_on:
      - rabbitmq
    ports:
      - "5132:5132"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin
    restart: on-failure

volumes:
  rabbitmq_data:
